/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolcouncillogin;
import java.awt.Component;
import javax.swing.JOptionPane;
/**
 * @author S346902018
 */
public class startScreen extends javax.swing.JFrame {
    
    createNewTxt newFile = new createNewTxt();
    private Component frame;
    
    //Creates new form startScreen
    public startScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        directoryEntry = new javax.swing.JTextField();
        startTitle = new javax.swing.JLabel();
        startSubTitle1 = new javax.swing.JLabel();
        startSubTitle2 = new javax.swing.JLabel();
        startEnterb = new javax.swing.JButton();
        newFileToggle = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 255));

        jPanel1.setBackground(new java.awt.Color(71, 0, 179));

        directoryEntry.setText("e.g: C:\\Users\\Documents\\logins.txt");
        directoryEntry.setToolTipText("");
        directoryEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directoryEntryActionPerformed(evt);
            }
        });

        startTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        startTitle.setForeground(new java.awt.Color(255, 255, 255));
        startTitle.setText("Please Enter a File Location");
        startTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        startSubTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        startSubTitle1.setForeground(new java.awt.Color(255, 255, 255));
        startSubTitle1.setText("Leave blank for default location.");

        startSubTitle2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        startSubTitle2.setForeground(new java.awt.Color(255, 255, 255));
        startSubTitle2.setText("If there is no default it will be placed in the project file");

        startEnterb.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        startEnterb.setText("Enter");
        startEnterb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startEnterbActionPerformed(evt);
            }
        });

        newFileToggle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newFileToggle.setText("New File?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(directoryEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(startTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(startSubTitle1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(startSubTitle2)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(newFileToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startEnterb, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(startTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startSubTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startSubTitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(directoryEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newFileToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startEnterb, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //wont be needed
    private void directoryEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directoryEntryActionPerformed
        
    }//GEN-LAST:event_directoryEntryActionPerformed
    
   
    private void startEnterbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startEnterbActionPerformed
        String directory = directoryEntry.getText();
        ProgressSaving save = new ProgressSaving();
        
        directory = save.fixFileLocation(directory);
        if (!save.testSave(directory) && !newFileToggle.isSelected()) { // if it doesn't already exist
            newFile.setSaveTo(directory);
            newFile.show();
        } else if (newFileToggle.isSelected()) {
            
            if (save.newSave(directory)) {
                SchoolCouncilLogin.saveDirectory = directory;
                LoginGUI lgui = new LoginGUI();
                lgui.show();
                
                this.dispose();
                
            } else {
                JOptionPane.showMessageDialog(frame,
                "File could not be created.",
                "File Creation Error",
                JOptionPane.ERROR_MESSAGE);
            }
        
        } else {
            LoginGUI lgui = new LoginGUI();
            lgui.show();
            //SchoolCouncilLogin closeSelfVar = new SchoolCouncilLogin();
            //closeSelfVar.setSaveDirectory(directory);
            SchoolCouncilLogin.saveDirectory = directory;
            
            this.dispose();
        }
    }//GEN-LAST:event_startEnterbActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(startScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(startScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(startScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(startScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new startScreen().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField directoryEntry;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton newFileToggle;
    private javax.swing.JButton startEnterb;
    private javax.swing.JLabel startSubTitle1;
    private javax.swing.JLabel startSubTitle2;
    private javax.swing.JLabel startTitle;
    // End of variables declaration//GEN-END:variables
}
